services:
    algolia.client:
        class: AlgoliaSearch\Client
        arguments:
            - ~ # Injected by configuration
            - ~ # Injected by configuration

    algolia.metadata_loader:
        class: Algolia\AlgoliaSearchBundle\Mapping\Loader\AnnotationLoader

    algolia.indexer:
        class: Algolia\AlgoliaSearchBundle\Indexer\Indexer
        arguments:
            - '@algolia.client'
            - '@doctrine.orm.entity_manager'
            - '@algolia.metadata_loader'
            - '%kernel.environment%'

    algolia.indexer_subscriber:
        class: Algolia\AlgoliaSearchBundle\EventListener\AlgoliaSearchDoctrineEventSubscriber
        arguments:
            - '@algolia.indexer'
            - '@?logger'
        tags:
            - { name: doctrine.event_subscriber }
